use_frameworks!
platform :ios, '10.0'

target 'StanwoodUITestingCore_Example' do
  pod 'StanwoodUITestingCore', :path => '../'

  target 'StanwoodUITestingCore_Tests' do
    inherit! :search_paths

    
  end
end
